version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    command: python api/main.py
    volumes:
      - .:/app

  bot:
    build: .
    command: python bot/run.py
    volumes:
      - .:/app